apiVersion: v1
kind: Service
metadata:
  name: siddu-service
spec:
  type: NodePort
  selector:
    app: siddu
  ports:
    - protocol: TCP
      port: 80        # port exposed inside cluster
      targetPort: 5000  # container port
      nodePort: 30007   # port to access externally via minikube node
